spring:
  application:
    name: dubbo-provider-1


project:
  service:
    version: 1.0.0
dubbo:
  scan:
    base-packages: com.lsy.dubbo.provider2.service.impl
  application:
    name: ${spring.application.name}
  protocol:
    port: 20880
    name: dubbo
    id: dubbo
  registry:
    address: zookeeper://127.0.0.1:2182?backup=127.0.0.1:2183,127.0.0.1:2184